name: Install and configure AppMap
description:
  Installs AppMap tools and the AppMap language library, and configures AppMap options for the
  project.
inputs:
  appmap-config:
    description: appmap.yml configuration contents.
  project-type:
    description: |
      Type of project to be configured. Valid values include bundler, yarn, npm, gradle, maven, 
      pip, pipenv, and poetry. Consult https://appmap.io/docs/add-appmap-to-a-project.html for
      more information.
  build-file:
    description: |
      Build file to be configured, in case of ambiguity. This is an advanced option.
  installer-name:
    description: |
      Installer name to be used, in case of ambiguity. This is an advanced option.
  tools-url:
    description:
      URL to the AppMap tools. By default, the latest version will be downloaded and installed.
  github-token:
    description: |
      The GitHub token to use with the GitHub API to enumerate AppMap Tools releases.
      Most commonly, you'll use `secrets.GITHUB_TOKEN`, which is automatically provided by GitHub.
  ignore-dot-appmap:
    description: |
      Add the .appmap directory to .gitignore, if it's not already present.
    default: true
  install-appmap-tools:
    description: |
      Install the AppMap command-line tools.
    default: true
  install-appmap-library:
    description: |
      Install the and configure the AppMap language library.
    default: true
  build-patch-file:
    description: |
      Create a patch file of changes made by the installer.
    default: true
  diff-path-spec:
    description: |
      Path specification to use when creating the patch file. If the patch file includes files that you don't want
      to commit, you can use this option to exclude them.
    default: ". ':(exclude,top)vendor' ':(exclude,top)node_modules'"
  verbose:
    description: Enable verbose logging.
    default: false
outputs:
  patch:
    description: Patch file of changes made by the installer.
runs:
  using: 'node16'
  main: 'dist/index.js'
