name: Archive AppMaps on PR merge

on:
  pull_request:
    types:
      - closed

env:
  APPMAP_TELEMETRY_DISABLED: 'true'

jobs:
  appmap_archive_main:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout step
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Install and configure AppMap tools
        uses: ./
        with:
          verbose: true
      - name: Build AppMaps
        run: yarn appmap
      - name: Archive AppMaps
        uses: getappmap/archive-appmap-action@v1-pre.10
        with:
          verbose: true
