name: Main

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

env:
  APPMAP_TELEMETRY_DISABLED: 'true'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependency libraries
        run: yarn install

      - name: Install and configure AppMap
        id: appmap-install
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-type: yarn
          verbose: true

      - name: Commit AppMap configuration changes
        uses: EndBug/add-and-commit@v7
        with:
          add: .
          message: 'chore: Update AppMap installation'

      - name: Build
        run: yarn package

      - name: Test
        id: test
        run: yarn appmap

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: dist
          message: 'chore: Packaged distribution of the GitHub action'

      - name: Archive AppMaps
        if: github.event_name != 'pull_request'
        uses: getappmap/archive-action@v1-pre.13

      - name: Analyze AppMaps
        if: ( success() || failure() ) && github.event_name == 'pull_request'
        uses: getappmap/analyze-action@v1-pre.14
        with:
          base-revision: ${{ github.event.pull_request.base.sha }}
          head-revision: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
