on: [push]

jobs:
  install_appmap_job:
    runs-on: ubuntu-latest
    name: Install AppMap
    steps:
      - name: Checkout step
        uses: actions/checkout@v3
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Package
        run: yarn package
      - name: Store build artifact
        uses: actions/upload-artifact@v2
        with:
          name: getappmap/install-action
          path: dist
