on: [push]

jobs:
  install_appmap_job:
    runs-on: ubuntu-latest
    name: Install AppMap
    steps:
      - name: Checkout step
        uses: actions/checkout@v3
      - name: Install AppMap step
        uses: ./
        id: install-appmap
